[connections.snowflake]
account = "VPKAUTI-FRB24108"
user = "PHANCK"
password = "qazx123(SNOWFLAKE)"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
